### PR TITLE
add map.resize() to make map responsive

### PR DESCRIPTION
**Pull request by justmarkup**
see #12 

This PR adds the function map.resize() which can be attached to an eventlistener, eg:

```
window.addEventListener('resize', function(event){
    map.resize();
});
```

I didn't add a resize eventlistener directly into datamap cause this way people can decide when they want to call map.resize() as some use smartresize or the like.

I also didn't add the CSS to make the svg responsive directly in datamap, you can see an example CSS in src/responsive.html

@markmarkoh I am not sure if I coded everything according to your preferences, so if you have any questions, improvements... let me know.

### CODE REVIEW

**Comment by markmarkoh** [comment]
@justmarkup sorry about the delay. Holiday time here, haven't had much computer time. I'm updating the docs and merging this in today.

Thanks so much for your work on this!

**Comment by justmarkup** [comment]
Awesome, thanks :+1: and a Happy New Year!

**Comment by shprink** [comment]
:+1:  Thanks guys!

**Comment by shprink** [comment]
Lastest tag was: Aug 27, 2014
Do you plan to tag this soon?

**Comment by markmarkoh** [comment]
@shprink I do, it just needs more testing before it's openly released.

**Pull request merged**
