### PR TITLE
High resolution map

### PR DESCRIPTION
**Pull request by magic890**
This merge will solve all the missing countries listed in #241 and #76 
adding new high resolution versions for `world` and `all` DataMaps (i.e. `datamaps.world.hires.js`, `datamaps.world.hires.min.js`, `datamaps.all.hires.js`, `datamaps.all.hires.min.js`).

### CODE REVIEW

**Comment by markmarkoh** [comment]
It looks like this PR has all your commits from the arc popup. Can you resubmit with just the hi-res related commits?

Also, what are the new file sizes of the built files (in kB)?

**Comment by magic890** [comment]
Sorry for the arc history. I think that if you merge it right now it would be fine because you have already merged the arc PR.

`datamaps.world.hires.js` - ~507KB
`datamaps.world.hires.min.js` - ~486KB
`datamaps.all.hires.js` - ~536KB
`datamaps.all.hires.min.js` - ~512KB

About twice the dimension of the standard one.

**Comment by magic890** [comment]
@markmarkoh any update? Are you ready to merge it?
I need this feature plus the merged #276 in the next release.

**Comment by markmarkoh** [comment]
@magic890 This is great, thanks for your work on this. I plan on making a bigger/more detailed announcement of this new enhancement.

**Pull request merged**
