### PR TITLE
add option to update bubbles in place when lat/lng unchanged

### PR DESCRIPTION
**Pull request by thebenedict**
I have bubble values that change slightly each year. The default behavior of `.bubbles([])` is to replace all, which makes it hard to notice small changes. This adds an option to grow/shrink existing bubbles to the new size. Click the year buttons to see the difference:

[Original behavior](http://embed.plnkr.co/YhzplFyYkupe88E2bVjz/preview) / [New behavior](http://embed.plnkr.co/l181GzZbRL8YYZesDBg9/preview)

Thanks for the great library!

### CODE REVIEW

**Comment by markmarkoh** [comment]
@thebenedict utilizing the 2nd parameter `.data()` is a great way to get this functionality.

There seems to be a disparity in the names of the update options, `update` and `updateBubbles`. Are those not meant to be the same?

Is there any sane way we could avoid using an option here at all? Like having `getBubblesKey` check for an `id` property and returning that? (possibly concatenated with `lat`/`lng`), otherwise returning a `stringified` version of the object?

Putting this behind an option (like in this PR) is best for backwards compatibility, but using an `id` property would be pretty slick.

**Comment by thebenedict** [comment]
Thanks for the feedback. Yes, they should be the same.

I was thinking along similar lines but got stuck on what the `id` should be. How about we follow d3's lead and let it be a function? Here it's configurable as an option, with the original `JSON.stringify` as the default for backwards compatibility.

**Comment by markmarkoh** [comment]
Where would that function be declared? We could have a default function option that checks for `id`, uses that, falls back to `JSON.stringify`, and that function could be overwritten as long as it returns a string.

Is that the direction you meant?

**Comment by thebenedict** [comment]
I'd like to avoid asking the user to provide an explicit `id` if possible, but what qualifies a bubble as "the same" as an existing bubble (so it should be updated instead of replaced) might depend on the use case. So the user would declare the function in their own code, and pass it as a config option to `bubbles()`. For example only lat/lng matters to me so in my client code I have:

```
      var bubbleKey = function (d) {
        return JSON.stringify({lat: d.latitude, lng: d.longitude});
      }

     map.bubbles(myArrayOfBubbleObjects, { keyFn: bubbleKey });
```
but other users might want
```
      var bubbleKey = function (d) {
        return JSON.stringify({lat: d.latitude, lng: d.longitude, foo: d.foo});
      }
```
or any arbitrary function that returns a string. And `JSON.stringify` is the default value of the `keyFn` option so nothing changes for existing users.

Is there an advantage to having an explicit `id`? I'm open to it.

**Comment by markmarkoh** [comment]
@thebenedict I think that approach is fine. If people did have a unique id, they could easily override the `keyFn` function to just saw `keyFn = (data) => data.id` or something.

We just need a better name for `keyFn`.

**Comment by thebenedict** [comment]
@markmarkoh Sounds good. How about just `key`? Maybe not descriptive, but consistent with the [underlying d3 function](https://github.com/mbostock/d3/wiki/Selections#data) it's passed to.

**Comment by markmarkoh** [comment]
Sounds good ot me.

**Comment by thebenedict** [comment]
@markmarkoh Changed in 2a8fa57.

Thanks again.

**Pull request merged**
