### PR TITLE
fix to support windows build

### PR DESCRIPTION
**Pull request by shailendher**
currently building the application in windows is not possible due to usage of restricted file names ('nul'). This fix is to overcome that limitation.

fixes: #337, #243 
reference: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

### CODE REVIEW

**Comment by denisnikolayev** [comment]
@markmarkoh can you please approve this pull request? we have the same issue and it's really hard to deal with it

**Comment by bbakermmc** [comment]
Is there a release that contains this fix?

**Comment by joelvaneenwyk** [comment]
Can someone please merge this?

**Comment by srogers909** [comment]
This code needs to be merged in, big time.

**Pull request merged**
