### PR TITLE
Support for popup on arc

### PR DESCRIPTION
**Pull request by magic890**
- Add support for popup on arc.
- Small improvements to README (added missing default parameter and color fill instructions).
- Standardised one liner code comments ( // Uppercase text ).

### CODE REVIEW

**Comment by magic890** [comment]
@markmarkoh I think it's ready for merge. Let me know your feedbacks.

**Comment by markmarkoh** [comment]
@magic890 Can you add an example `.html` file with this working?

**Comment by magic890** [comment]
Example created `src/examples/arc-with-popup.html`.
@markmarkoh are you able to merge it now?

**Comment by markmarkoh** [comment]
@magic890 No need for the `dist` files, I'll generate those (in the future, probably move them to `npm postinstall` if bower has the equivalent). 

Thanks for your work on this.

**Pull request merged**
