### PR TITLE
Add Typescript definition file

### PR DESCRIPTION
**Pull request by JasonKaz**

### CODE REVIEW

**Comment by cemberkongay** [comment]
PR? What does it mean? Could you give me some more detail?


*Cem Berk ÖNGAY    *

2017-08-21 16:57 GMT+03:00 Jason Kaczmarsky <notifications@github.com>:

**Comment by jackmahoney** [comment]
Me too. Can somebody deploy to NPM please cc @markmarkoh

**Comment by Miguelito777** [comment]
i trying to use the definition file in my angular2 app, but i get the following error: 
../path/datamaps/index.d.ts' is not a module.
somebody already implemented this definition file?
how to did?

i'm following this post how my gia: 
https://hackernoon.com/how-to-use-javascript-libraries-in-angular-2-apps-ff274ba601af

**Comment by walterspieler** [comment]
@Miguelito777 try this:
`import 'datamaps';`
`const map = new DataMap();` should work then.  
TypeScript knows DataMaps variable.

**Comment by perjerz3434** [comment]
Me too

**Comment by amansharma1904** [comment]
import * as Datamap from 'node_modules/datamaps/dist/datamaps.world.min.js';

**Comment by amansharma1904** [comment]
import * as Datamap from 'node_modules/datamaps/dist/datamaps.world.min.js';

This worked for me. I was working with the worldMap for my Angular 7 project.

**Comment by snuuuz** [comment]
@JasonKaz, Should `DataMap` be `Datamap` (i.e. lowercase m) in your index.d.ts? When I include the TS definition via
```
/// <reference types="datamaps" />
```
I get a TS compile error:
```
ERROR in /Users/michael/_git/.../xxx.ts
[tsl] ERROR in /Users/michael/_git/.../xxx.ts(626,9)
      TS2552: Cannot find name 'Datamap'. Did you mean 'DataMap'?
```
Currently, I am getting around it with this temporary declaration hack:
```
/// <reference types="datamaps" />
declare class Datamap { constructor(options: DataMapOptions); }  // Temp hack
```

**Pull request merged**
