### PR TITLE
Add support for aspectRatio for easier display of responsive custom maps

### PR DESCRIPTION
**Pull request by adrianbj**
Sorry about the whitespace changes (automatic sublime setting). Let me know if you'd prefer a revised PR without these changes.

### CODE REVIEW

**Comment by justmarkup** [comment]
Hi @adrianbj 

Thanks for the PR, if you please could remove the whitespace changes I am happy to merge it.

**Comment by adrianbj** [comment]
Looks like I have reverted all the whitespace/newline issues.

Thanks!

**Comment by justmarkup** [comment]
Looking good. Thanks @adrianbj

**Comment by adrianbj** [comment]
Just wanted to mention that I have been playing around with d3.geo.bounds() and found that it is possible to get the aspect ratio that way, so maybe that should be used to calculate the default instead of hardcoding the 0.5625. I think it is still potentially nice to have the configurable aspectRation option because it allows for more precise padding configuration.

I have also been playing around with automatic calculation of center, scale, and translate values. Would it make sense to also calculate these as defaults with the option to override? Of course the scale is tricky when doing responsive and not setting dimensions.

Not really sure - maybe it is complicating things - what do you think?

**Pull request merged**
